#!/usr/bin/env python3
"""Adapter-API compat suite for ``materialize_agent`` (extraction plan §2,
gray zone 4) — the adapter-API compat test the plan promises alongside the
protocol conformance suite.

Golden-string proof: each built-in adapter renders an AgentDef to discovery-
file text byte-identical to the client's pre-extraction renderer output
(sync_agents' render_claude/render_codex, captured before deletion), with
the caller-supplied header wrapped in the adapter's own comment dialect.
Render constraints raise RunnerError(code='agent_render') naming the
harness: the codex ''' ban and the claude unsupported-value type.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

import os as _os

REPO = Path(__file__).resolve().parents[1]
# Runner-repo test header: point the runner's path constants at this repo,
# then put src/ on sys.path when agent_runner is not already importable (the
# no-pip stdlib run — the same path the GTM bootstrap shim relies on).
_os.environ.setdefault("AGENT_RUNNER_PROJECT_ROOT", str(REPO))
_os.environ.setdefault("RUNNER_PROJECT_ID", "testproj")
try:
    import agent_runner  # noqa: F401
except ImportError:
    sys.path.insert(0, str(REPO / "src"))

from agent_runner.harness import get_adapter  # noqa: E402
from agent_runner.harness.base import AgentDef  # noqa: E402
from agent_runner.runtime import RunnerError  # noqa: E402


# The fixture mirrors the sync_agents docstring example; the header is the
# client's GENERATED-marker convention, passed WITHOUT comment syntax — the
# adapter wraps it.
HEADER = (
    "GENERATED by core/sync_agents.py from prod-phase2-departments.agent.md"
    " — edit the source, then run: python3 core/sync_agents.py"
)
DESCRIPTION = 'Maps the university\'s academic departments — the "schools" list.'
BODY = "Find every academic department.\n\nReturn ONE JSON object; don't read local files.\n"

CLAUDE_AGENT = AgentDef(
    name="prod-phase2-departments",
    description=DESCRIPTION,
    config={
        "model": "claude-opus-4-6",
        "effort": "max",
        "disallowedTools": "Read Bash",
        "mcpServers": ["firecrawl"],
    },
    body=BODY,
)
CODEX_AGENT = AgentDef(
    name="prod-phase2-departments",
    description=DESCRIPTION,
    config={
        "model": "gpt-5.5",
        "model_reasoning_effort": "xhigh",
        "features": {"shell_tool": False},
    },
    body=BODY,
)

# Captured verbatim from sync_agents.render_claude / render_codex before the
# extraction-step-7 deletion — never regenerate from the adapters under test.
CLAUDE_GOLDEN = (
    "---\n"
    "# GENERATED by core/sync_agents.py from prod-phase2-departments.agent.md"
    " — edit the source, then run: python3 core/sync_agents.py\n"
    'name: "prod-phase2-departments"\n'
    'description: "Maps the university\'s academic departments — the \\"schools\\" list."\n'
    'model: "claude-opus-4-6"\n'
    'effort: "max"\n'
    'disallowedTools: "Read Bash"\n'
    "mcpServers:\n"
    '  - "firecrawl"\n'
    "---\n"
    "\n"
    "Find every academic department.\n"
    "\n"
    "Return ONE JSON object; don't read local files.\n"
)
CODEX_GOLDEN = (
    "# GENERATED by core/sync_agents.py from prod-phase2-departments.agent.md"
    " — edit the source, then run: python3 core/sync_agents.py\n"
    'name = "prod-phase2-departments"\n'
    'description = "Maps the university\'s academic departments — the \\"schools\\" list."\n'
    'model = "gpt-5.5"\n'
    'model_reasoning_effort = "xhigh"\n'
    "features = { shell_tool = false }\n"
    "developer_instructions = '''\n"
    "Find every academic department.\n"
    "\n"
    "Return ONE JSON object; don't read local files.\n"
    "'''\n"
)


class ClaudeMaterializeTest(unittest.TestCase):
    def test_golden_discovery_file_text(self) -> None:
        rendered = get_adapter("claude").materialize_agent(CLAUDE_AGENT, header=HEADER)
        self.assertEqual(rendered, CLAUDE_GOLDEN)
        # Header wrapping: the bare header string arrives INSIDE the YAML
        # frontmatter as a `# ` comment line; body keeps its trailing newline.
        self.assertEqual(rendered.split("\n")[1], f"# {HEADER}")
        self.assertTrue(rendered.endswith(BODY))

    def test_unsupported_value_type_raises_naming_claude(self) -> None:
        broken = AgentDef(
            name=CLAUDE_AGENT.name,
            description=CLAUDE_AGENT.description,
            config={"mcpServers": {"firecrawl": {"transport": "stdio"}}},
            body=BODY,
        )
        with self.assertRaises(RunnerError) as ctx:
            get_adapter("claude").materialize_agent(broken, header=HEADER)
        self.assertEqual(ctx.exception.code, "agent_render")
        self.assertFalse(ctx.exception.retryable)
        self.assertIn("claude", str(ctx.exception))


class CodexMaterializeTest(unittest.TestCase):
    def test_golden_discovery_file_text(self) -> None:
        rendered = get_adapter("codex").materialize_agent(CODEX_AGENT, header=HEADER)
        self.assertEqual(rendered, CODEX_GOLDEN)
        # Header wrapping: the bare header string becomes the first line as a
        # `# ` comment; the literal block closes with ''' plus newline.
        self.assertEqual(rendered.split("\n")[0], f"# {HEADER}")
        self.assertTrue(rendered.endswith("'''\n"))

    def test_triple_quote_body_raises_naming_codex(self) -> None:
        broken = AgentDef(
            name=CODEX_AGENT.name,
            description=CODEX_AGENT.description,
            config=CODEX_AGENT.config,
            body="Never write ''' in a prompt body.\n",
        )
        with self.assertRaises(RunnerError) as ctx:
            get_adapter("codex").materialize_agent(broken, header=HEADER)
        self.assertEqual(ctx.exception.code, "agent_render")
        self.assertFalse(ctx.exception.retryable)
        self.assertIn("codex", str(ctx.exception))
        self.assertIn("'''", str(ctx.exception))


if __name__ == "__main__":
    unittest.main()
